TensorFlow-张量的定义和基本运算

In [1]:
#导入TensorFlow
import tensorflow as tf

In [2]:
#张量的定义

#定义一个随机数（标量）
random_float=tf.random.uniform(shape=())

#定义一个有2个元素的零向量
zero_vector=tf.zeros(shape=(2))

#定义两个2×2的常量矩阵
A=tf.constant([[1.,2.],[3.,4.]])
B=tf.constant([[5.,6.],[7.,8.]])

In [3]:
#查看矩阵A的形状、和值

#矩阵A的形状
print(A.shape)

#矩阵A的类型
print(A.dtype)  

#矩阵A的值
print(A.numpy())

(2, 2)
<dtype: 'float32'>
[[1. 2.]
 [3. 4.]]


In [4]:
#计算矩阵A和B的和
C=tf.add(A, B)
print(C)

#计算矩阵A和B的乘积
D=tf.matmul(A, B) 
print(D)

tf.Tensor(
[[ 6.  8.]
 [10. 12.]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[19. 22.]
 [43. 50.]], shape=(2, 2), dtype=float32)
